# Generated by Django 3.2.9 on 2022-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.IntegerField(max_length=30)),
                ('city', models.IntegerField(max_length=20)),
            ],
        ),
    ]
