# Generated by Django 3.2.9 on 2022-03-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220322_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='myimage',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
